"""core schema

Revision ID: 4263928d0e6c
Revises: 0001
Create Date: 2026-07-16 08:58:59.016582

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "4263928d0e6c"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orgs",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "org_type",
            sa.Enum(
                "local",
                "diaspora",
                "foreign",
                name="org_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orgs_deleted_at"), "orgs", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_orgs_org_type"), "orgs", ["org_type"], unique=False)
    op.create_table(
        "run_ledger",
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("ref", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "success",
                "failed",
                name="run_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("items_seen", sa.Integer(), nullable=False),
        sa.Column("items_created", sa.Integer(), nullable=False),
        sa.Column("items_updated", sa.Integer(), nullable=False),
        sa.Column("items_unchanged", sa.Integer(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("error_kind", sa.String(length=64), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_run_ledger_kind"), "run_ledger", ["kind"], unique=False)
    op.create_index(op.f("ix_run_ledger_status"), "run_ledger", ["status"], unique=False)
    op.create_table(
        "sources",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "html_static",
                "html_dynamic",
                "pdf",
                "api",
                name="source_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("fetch_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cron", sa.String(length=64), nullable=False),
        sa.Column("rate_limit_per_min", sa.Integer(), nullable=False),
        sa.Column(
            "tos_status",
            sa.Enum(
                "unreviewed",
                "allowed",
                "restricted",
                "prohibited",
                name="tos_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sources_enabled"), "sources", ["enabled"], unique=False)
    op.create_index(op.f("ix_sources_key"), "sources", ["key"], unique=True)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "company_profiles",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("sectors", postgresql.ARRAY(sa.TEXT()), nullable=False),
        sa.Column("capabilities", postgresql.ARRAY(sa.TEXT()), nullable=False),
        sa.Column("certifications", postgresql.ARRAY(sa.TEXT()), nullable=False),
        sa.Column("regions", postgresql.ARRAY(sa.TEXT()), nullable=False),
        sa.Column("profile_embedding", pgvector.sqlalchemy.Vector(dim=1024), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_company_profiles_deleted_at"), "company_profiles", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_company_profiles_org_id"), "company_profiles", ["org_id"], unique=True)
    op.create_table(
        "org_members",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "admin",
                "member",
                name="org_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "user_id", name="uq_org_members_org_user"),
    )
    op.create_index(op.f("ix_org_members_org_id"), "org_members", ["org_id"], unique=False)
    op.create_index(op.f("ix_org_members_user_id"), "org_members", ["user_id"], unique=False)
    op.create_table(
        "tenders",
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("source_tender_id", sa.String(length=255), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("buyer", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("region", sa.String(length=128), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closing_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opening_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bid_bond_minor", sa.Integer(), nullable=True),
        sa.Column("bid_bond_currency", sa.String(length=3), nullable=True),
        sa.Column("doc_price_minor", sa.Integer(), nullable=True),
        sa.Column("doc_price_currency", sa.String(length=3), nullable=True),
        sa.Column(
            "bidding_track",
            sa.Enum(
                "ncb",
                "icb",
                "donor",
                "private",
                "unknown",
                name="bidding_track",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1024), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "source_tender_id", name="uq_tenders_source_ref"),
    )
    op.create_index(op.f("ix_tenders_bidding_track"), "tenders", ["bidding_track"], unique=False)
    op.create_index(op.f("ix_tenders_closing_at"), "tenders", ["closing_at"], unique=False)
    op.create_index(
        "ix_tenders_raw_data", "tenders", ["raw_data"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_tenders_source_id"), "tenders", ["source_id"], unique=False)
    op.create_table(
        "matches",
        sa.Column("tender_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column(
            "eligibility",
            sa.Enum(
                "eligible",
                "conditional",
                "ineligible",
                "unknown",
                name="eligibility_verdict",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "new",
                "saved",
                "dismissed",
                name="match_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tender_id"], ["tenders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tender_id", "org_id", name="uq_matches_tender_org"),
    )
    op.create_index(op.f("ix_matches_org_id"), "matches", ["org_id"], unique=False)
    op.create_index(op.f("ix_matches_state"), "matches", ["state"], unique=False)
    op.create_index(op.f("ix_matches_tender_id"), "matches", ["tender_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_matches_tender_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_state"), table_name="matches")
    op.drop_index(op.f("ix_matches_org_id"), table_name="matches")
    op.drop_table("matches")
    op.drop_index(op.f("ix_tenders_source_id"), table_name="tenders")
    op.drop_index("ix_tenders_raw_data", table_name="tenders", postgresql_using="gin")
    op.drop_index(op.f("ix_tenders_closing_at"), table_name="tenders")
    op.drop_index(op.f("ix_tenders_bidding_track"), table_name="tenders")
    op.drop_table("tenders")
    op.drop_index(op.f("ix_org_members_user_id"), table_name="org_members")
    op.drop_index(op.f("ix_org_members_org_id"), table_name="org_members")
    op.drop_table("org_members")
    op.drop_index(op.f("ix_company_profiles_org_id"), table_name="company_profiles")
    op.drop_index(op.f("ix_company_profiles_deleted_at"), table_name="company_profiles")
    op.drop_table("company_profiles")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_sources_key"), table_name="sources")
    op.drop_index(op.f("ix_sources_enabled"), table_name="sources")
    op.drop_table("sources")
    op.drop_index(op.f("ix_run_ledger_status"), table_name="run_ledger")
    op.drop_index(op.f("ix_run_ledger_kind"), table_name="run_ledger")
    op.drop_table("run_ledger")
    op.drop_index(op.f("ix_orgs_org_type"), table_name="orgs")
    op.drop_index(op.f("ix_orgs_deleted_at"), table_name="orgs")
    op.drop_table("orgs")
    # ### end Alembic commands ###
