"""add tender_documents table

Revision ID: 48419dc0e4ac
Revises: 7be520ec3e8f
Create Date: 2026-07-24 11:01:32.363449

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "48419dc0e4ac"
down_revision: str | None = "7be520ec3e8f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tender_documents",
        sa.Column("tender_id", sa.UUID(), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "parse_method",
            sa.Enum(
                "pdfium",
                "ocr",
                "docling",
                name="document_parse_method",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("detected_language", sa.String(length=8), nullable=True),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tender_id"], ["tenders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tender_documents_storage_key"), "tender_documents", ["storage_key"], unique=False
    )
    op.create_index(
        op.f("ix_tender_documents_tender_id"), "tender_documents", ["tender_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tender_documents_tender_id"), table_name="tender_documents")
    op.drop_index(op.f("ix_tender_documents_storage_key"), table_name="tender_documents")
    op.drop_table("tender_documents")
    # ### end Alembic commands ###
