"""add qualifications table

Revision ID: 677995c87c69
Revises: 4263928d0e6c
Create Date: 2026-07-24 01:42:50.184837

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "677995c87c69"
down_revision: str | None = "4263928d0e6c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "qualifications",
        sa.Column("tender_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "qualified",
                "rejected",
                "needs_review",
                name="qualification_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "urgency",
            sa.Enum(
                "urgent",
                "soon",
                "normal",
                "unknown",
                name="qualification_urgency",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("sector", sa.String(length=128), nullable=True),
        sa.Column("reasons", postgresql.ARRAY(sa.TEXT()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "rule",
                "llm",
                name="qualification_method",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "corrected_status",
            sa.Enum(
                "qualified",
                "rejected",
                "needs_review",
                name="qualification_status_corrected",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("correction_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tender_id"], ["tenders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_qualifications_status"), "qualifications", ["status"], unique=False)
    op.create_index(
        op.f("ix_qualifications_tender_id"), "qualifications", ["tender_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_qualifications_tender_id"), table_name="qualifications")
    op.drop_index(op.f("ix_qualifications_status"), table_name="qualifications")
    op.drop_table("qualifications")
    # ### end Alembic commands ###
