"""add eligibility_assessments cache table

Revision ID: 68300cfde630
Revises: a1c3e8f92b71
Create Date: 2026-07-30 12:43:21.290887

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "68300cfde630"
down_revision: str | None = "a1c3e8f92b71"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eligibility_assessments",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("tender_id", sa.UUID(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum(
                "eligible",
                "conditional",
                "ineligible",
                "unknown",
                name="eligibility_verdict",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reasons", postgresql.ARRAY(sa.TEXT()), nullable=False),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("law_version", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["orgs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tender_id"], ["tenders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "tender_id", name="uq_eligibility_org_tender"),
    )
    op.create_index(
        op.f("ix_eligibility_assessments_org_id"),
        "eligibility_assessments",
        ["org_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_eligibility_assessments_tender_id"),
        "eligibility_assessments",
        ["tender_id"],
        unique=False,
    )
    # Autogenerate also proposed `op.alter_column("tenders", "group_id",
    # nullable=True)` here -- a pre-existing, unrelated drift between the ORM
    # model's `uuid.UUID | None` annotation and the live DB's real `NOT NULL`
    # constraint (set deliberately in a1c3e8f92b71 per ADR-028; the model
    # annotation was never updated to match). Removed: altering an existing
    # table is founder-review-mandatory (AGENTS.md rule 14) and unrelated to
    # this migration's actual purpose -- flagged separately, not fixed here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_eligibility_assessments_tender_id"), table_name="eligibility_assessments"
    )
    op.drop_index(op.f("ix_eligibility_assessments_org_id"), table_name="eligibility_assessments")
    op.drop_table("eligibility_assessments")
    # ### end Alembic commands ###
