"""add notifications_log table

Revision ID: 7be520ec3e8f
Revises: 90191123b5aa
Create Date: 2026-07-24 10:42:50.998019

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7be520ec3e8f"
down_revision: str | None = "90191123b5aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications_log",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tender_id", sa.UUID(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "email",
                "telegram",
                name="notification_channel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "event_type",
            sa.Enum(
                "digest",
                "instant",
                name="notification_event_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tender_id"], ["tenders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "tender_id", "channel", "event_type", name="uq_notifications_log_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_notifications_log_channel"), "notifications_log", ["channel"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_log_event_type"), "notifications_log", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_log_idempotency_key"),
        "notifications_log",
        ["idempotency_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_notifications_log_tender_id"), "notifications_log", ["tender_id"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_log_user_id"), "notifications_log", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notifications_log_user_id"), table_name="notifications_log")
    op.drop_index(op.f("ix_notifications_log_tender_id"), table_name="notifications_log")
    op.drop_index(op.f("ix_notifications_log_idempotency_key"), table_name="notifications_log")
    op.drop_index(op.f("ix_notifications_log_event_type"), table_name="notifications_log")
    op.drop_index(op.f("ix_notifications_log_channel"), table_name="notifications_log")
    op.drop_table("notifications_log")
    # ### end Alembic commands ###
