"""add law_chunks table

Revision ID: 90191123b5aa
Revises: b8709aa823de
Create Date: 2026-07-24 08:00:20.088140

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

revision: str = "90191123b5aa"
down_revision: str | None = "b8709aa823de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "law_chunks",
        sa.Column("document_name", sa.String(length=255), nullable=False),
        sa.Column("document_url", sa.Text(), nullable=False),
        sa.Column("article_ref", sa.String(length=64), nullable=False),
        sa.Column("text_en", sa.TEXT(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1024), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_law_chunks_article_ref"), "law_chunks", ["article_ref"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_law_chunks_article_ref"), table_name="law_chunks")
    op.drop_table("law_chunks")
    # ### end Alembic commands ###
